### PR TITLE
default port of cloudflare is 54

### PR DESCRIPTION
**Pull request by bhuism**

### CODE REVIEW

**Comment by cjk** [comment]
Hi @bhuism , thanks for the PR - one question, what is the advantage of changing the port from 5054 to 54 ?

**Comment by cjk** [comment]
The reason why port #5054 was chosen over #54 is explained here: https://github.com/visibilityspots/dockerfile-cloudflared/commit/330e1383c1f611bcf5b05ee07f3524f0bfcb084e

**Comment by bhuism** [comment]
a, ok

**Comment by bhuism** [comment]
> Hi @bhuism , thanks for the PR - one question, what is the advantage of changing the port from 5054 to 54 ?

it's the default of the cloudflare container

**Pull request closed without merging**
